export const RECOMMENDMUSIC = 'RECOMMENDMUSIC';
export const RECOMMENDMUSIC_SUC = 'RECOMMENDMUSIC_SUC';
export const FETCH_RECOMMENDMUSIC_INFO = 'FETCH_RECOMMENDMUSIC_INFO';
export const FETCH_RECOMMENDMUSIC_INFO_SUC = 'FETCH_RECOMMENDMUSIC_INFO_SUC';
export const FETCH_NEWMUSIC_INFO = 'FETCH_NEWMUSIC_INFO';
export const FETCH_NEWMUSIC_INFO_SUC = 'FETCH_NEWMUSIC_INFO_SUC';
export const FETCH_Recommend_DELETE = 'FETCH_Recommend_DELETE';
export const FETCH_RECOMMEND_RENAME = 'FETCH_RECOMMEND_RENAME';
export const FETCH_MULITIDELETE = 'FETCH_MULITIDELETE';
export const FETCH_MULITI = 'FETCH_MULITI';

